### ISSUE TITLE
'music_player/music_player-Swift.h' file not found

### ISSUE THREAD

**Issue by curiosity654** [whiteHatpro/flutter_music_plugin#1]
Hi, thank you for the code. I would like to know that will this repo be maintained?
From my understanding, this plugin will enable flutter to control the system media (.i.e, the play and stop of another music app), which is what I'm looking for. But the plugin does not have an example, and I met the problem mentioned in the title.
Will there be updates on the code? Looking forward to your reply.

**Comment by whiteHatpro** [comment]
hey @curiosity654 
yes right now I am involved in some other project. I will be again starting with this project after some time
and yes the project is a flutter plugin that will control the system media.
DO follow me and the repo for future updates
